### ISSUE TITLE
yarn develop is not successful

### ISSUE THREAD

**Issue by ohkimchi** [timhagn/gbitest#1]
yarn run v1.10.1
warning ../package.json: No license field
error Command "develop" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I tried to run this repo, but the command `yarn develop` is not successful

**Comment by timhagn** [comment]
Hi @ohkimchi!

Thanks for bringing this up, though I gonna have to get back to your issue tomorrow,
cause my wife and I are celebrating our 12th relationship anniversary,
so no coding for me today : )!

But if you were be so kind and would give me your results of running `gatsby info`,
I'd have a better starting point at once.

Read you tomorrow,

Tim.

**Comment by ohkimchi** [comment]
lol no problem! Enjoy your time with you :D 
Here is my logs for `gatsby info`
`gatsby info

  System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.3.0 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 65.0.1
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.3.3 => 2.3.3
  npmGlobalPackages:
    gatsby-cli: 2.5.4`

**Comment by timhagn** [comment]
Hi @ohkimchi,

thanks for the good wishes to our family of 2 - was a nice evening / night (am still recuperating ; ).

But back to your issue: just tested with a fresh clone of `gbitest` and - am just guessing - might it be that you've missed running `yarn (install)` or `npm install` before trying to run `yarn develop`? Cause this I what I get before running either one of them with `gatsby info`:
```
  System:
    OS: Linux 4.15 Linux Mint 19.1 (Tessa)
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 11.13.0 - /usr/bin/node
    Yarn: 1.15.2 - /usr/bin/yarn
    npm: 6.9.0 - /usr/bin/npm
  Languages:
    Python: 2.7.15 - /usr/bin/python
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 66.0.1
  npmGlobalPackages:
    gatsby-cli: 2.4.17
```
with an error similar to yours when trying `yarn develop` - and this I get from `gatsby info` afterwards:
```
  System:
    OS: Linux 4.15 Linux Mint 19.1 (Tessa)
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 11.13.0 - /usr/bin/node
    Yarn: 1.15.2 - /usr/bin/yarn
    npm: 6.9.0 - /usr/bin/npm
  Languages:
    Python: 2.7.15 - /usr/bin/python
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 66.0.1
  npmPackages:
    gatsby: 2.3.4 => 2.3.4 
    gatsby-background-image: ^0.2.8-alpha4 => 0.2.8-alpha4 
    gatsby-image: ^2.0.35 => 2.0.35 
    gatsby-plugin-manifest: ^2.0.25 => 2.0.25 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-react-helmet: 3.0.11 => 3.0.11 
    gatsby-plugin-sharp: 2.0.32 => 2.0.32 
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7 
    gatsby-source-filesystem: ^2.0.28 => 2.0.28 
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17 
  npmGlobalPackages:
    gatsby-cli: 2.4.17
```
Am happy to help should this not have been the issue : )!

**Comment by timhagn** [comment]
Hi @ohkimchi!

Did you already get the chance to further test this so we might close this issue - or is anything still running amiss and `yarn develop` doesn't work for you?

Thanks in advance,

Tim.

**Comment by ohkimchi** [comment]
Hi @timhagn I am busy with some work tasks now. I will try as soon as I become available. Shouldn't be later than the end of today!

**Comment by ohkimchi** [comment]
@timhagn hey you are right, I think this issue can be closed now. I was testing with the this repo https://github.com/timhagn/gatsby-background-image , then maybe messed up with this one. Sorry for the confusion, the problem is gone now!

**Comment by timhagn** [comment]
@ohkimchi No problem at all, great it worked out : )!
Do you want to have the honors of closing this issue or shall I?

**Comment by ohkimchi** [comment]
@timhagn sure. Thanks Tim!

**Comment by timhagn** [comment]
You're welcome, I'm always happy to help : )!
