### ISSUE TITLE
Where to apply linear gradient color overlay (or any) for gatsby-background-image?

### ISSUE THREAD

**Issue by nemethricsi** [timhagn/gbitest#8]
Is there a proper way to apply overlay color for [`gatsby-background-image`](https://www.gatsbyjs.com/plugins/gatsby-background-image/)?

In native I had this one:

```css
background: linear-gradient(0deg, rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0)),
    url("./images/hero.jpg") center / cover no-repeat fixed;
```

and  I would like to apply this to my `BackgroundImage` component:

```jsx
<BackgroundImage
    style={{
        maxWidth: 1980,
        margin: '0 auto',
        backgroundAttachment: 'fixed',
        backgroundPosition: 'center',
        backgroundRepeat: 'no-repeat',
        backgroundSize: 'cover',
        backgroundColor: 'rgba(0, 0, 0, 0.5)', {/* What does this do here? Is it the background color before anthing loads in? */}
     }}
     Tag="section"
      fluid={imageData}
      fadeIn={`soft`}
      backgroundColor={`#000000`} {/* What does this do here? */}
 >
    {children}
 </BackgroundImage>
```

Thank you for your help!

**Comment by timhagn** [comment]
Hi  @nemethricsi,

don't know if you have studied the `README` of `gbi` a little bit more, meanhwile, but here's the relevant passage:
[How to Use with Multiple Images](https://github.com/timhagn/gatsby-background-image/tree/master/packages/gatsby-background-image#how-to-use-with-multiple-images).

Best,

Tim.
